name: FusionExport PDF Generator

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run FusionExport batch via PowerShell
        shell: pwsh
        run: |
          Write-Host "🚀 Running FusionExport via PowerShell..."
          & cmd /c run.bat

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: FusionExportPDF
          path: output/*.pdf
